baseURL = 'https://my2ndbrain.vercel.app'
languageCode = 'en-us'
title = 'Ultradian'

[params]
  description = "Mohammad Faisal's Knowledge Base"
  author = "Mohammad Faisal"
  sanityProjectId = "mvggkjnh"
  sanityDataset = "production"

[outputs]
  home = ["HTML", "JSON"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
